### PR TITLE
Add OWIPythonConnector widget

### PR DESCRIPTION
**Pull request by kernc**
##### Description of changes

IPython Connector widget for accessing local objects stored in IPython shell/Jupyter notebook with `%store` magic command. Auto-converts pd.DataFrame/pd.Series/np.ndarray objects into Tables.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by jerneju** [comment]
I think the same widget is in another add-on?

**Comment by kernc** [comment]
Thanks. It should now.

**Comment by jerneju** [comment]
Widget **Significant Groups** does not work properly. Could you please move that widget in a separate PR?

**Comment by kernc** [comment]
Both widgets work. Please pull Orange master and try again. 😛

**Pull request merged**
