### PR TITLE
OW1ka: EnKlikAnketa widget

### PR DESCRIPTION
**Pull request by kernc**
Likened to Google Sheets widget. Requires bs4.

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Please advise: where can I get the proper link in 1ka that will display the survey? Their GUI is a complete mess... 😒

**Comment by ajdapretnar** [comment]
Ok, I managed to test it somewhat.
It is fairly strange having a tooltip with a 'clickable' url, on which you cannot actually click. The tooltip is hidden as soon as I move the cursor. So I had a hard time finding help for setting up a survey link.

Then I followed the instructions and entered the right url. The survey got loaded (info box displayed, output present), but the url instantly defaulted to previous one and the error got displayed again. Does not happen when running --clear-widget-settings.

**Comment by ajdapretnar** [comment]
One more issue. Not sure whether this is a bug on our side or 1ka's, reporting it here anyway.

My survey:
screen shot 2017-09-19 at 10 27 52


Orange spreadsheet:
screen shot 2017-09-19 at 10 28 00

Instead of Izberi = A, it should be Izberi (Prvi) = A, Izberi (Drugi) = B, Izberi (Tretji) = C. And what are those missing features?

**Comment by kernc** [comment]
Hopefully resolved.

**Comment by ajdapretnar** [comment]
Yup, resolved.
I also like the new UserAdviceMessage. I think it is more informative than the old tooltip. 👍 

One final question/issue - Orange decides one of my columns is a string, even though I think it should be, say, categorical. Should we have the same functionality here as we do in the File widget or should we handle this differently? When importing data, you get somehow stuck with the option Orange 'guessed'.

**Comment by ajdapretnar** [comment]
An idea (not necessarily a good one) - should Edit Domain widget become more versatile and enable changes of attribute types?

**Comment by kernc** [comment]
> Edit Domain widget should become more versatile and enable changes of attribute types

My thoughts exactly.

**Comment by ajdapretnar** [comment]
Oh, and should we treat 'neodgovorjeno vprašanje' as nan or what? I am really not sure on this one...

**Comment by kernc** [comment]
Done.

**Pull request merged**
