### PR TITLE
OWCorrelations: Use heuristic to get the most promising attribute pairs

### PR DESCRIPTION
**Pull request by VesnaT**
When dataset is too big (i.e too many attributes or instances), it is impossible to calculate correlations for all attribute pairs. KMeans is used to suggest the most promising attribute pairs by selecting the pair within a cluster.

### CODE REVIEW

**Comment by BlazZupan** [comment]
Please sort the rows by absolute value of correlations. Also, keep the same precision when displaying numbers (e.g., instead of 0.76 write 0.760).

**Comment by BlazZupan** [comment]
Please show progress bar.

**Comment by VesnaT** [comment]
Do not merge until #2118 and #2117 are merged.

**Comment by ajdapretnar** [comment]
Since both necessary commits are merged, can we merge this one as well? @BlazZupan

**Comment by astaric** [comment]
@BlazZupan, this has been sitting here for more than a year. Is there still need for this widget? Do we ask @VesnaT to rebase, or do we close it as won't fix?

**Comment by ajdapretnar** [comment]
@VesnaT Could you please rebase so we can merge and hopefully include it in the migration of the widget? Thanks!

**Comment by BlazZupan** [comment]
It would be great if we can have this widget finally in Orange.

**Comment by VesnaT** [comment]
It's rebased, but the tests don't pass (I guess since vizrank has been changed). The tests should be fixed before the widget is moved to Orange.

**Comment by ajdapretnar** [comment]
Yeah, it's probably #155.

**Comment by VesnaT** [comment]
The last commit fixes #155

**Comment by ajdapretnar** [comment]
I have tried this and while it looks really good, I am getting a segfault when switching between Pearson and Spearman. I cannot easily replicate this, but it happens each and every time when using iris.tab, clicking on different feature pairs and switching between Pearson and Spearman. Normally I select a feature pair and then switch the method.

**Comment by ajdapretnar** [comment]
I merged this. I will have a look at the segfault issue and try to have it as replicable as possible. This will be a separate issue.

**Pull request merged**
