### PR TITLE
Remove create table

### PR DESCRIPTION
**Pull request by PrimozGodec**
Create table is moved to educational. 

**Merge this PR when https://github.com/biolab/orange3-educational/pull/106 is merged and the educational add-on is released**

### CODE REVIEW

**Comment by janezd** [comment]
Added to Educational in https://github.com/biolab/orange3-educational/pull/106.

**Comment by PrimozGodec** [comment]
@janezd I think you accidentally closed this PR since it looked like an issue. It should be merged to remove the Create table widget from prototypes.

**Comment by PrimozGodec** [comment]
But first, we must create an Orange3-educational release. I will create it tomorrow.

**Comment by janezd** [comment]
No, I wanted to merge it, not close it. I guess it could be merged because the PR in Educational is merged. But we shouldn't *release* Prototypes before releasing Educational. :)

Let's do it on Friday.

**Comment by PrimozGodec** [comment]
You are right. We can merge it and release both on Friday( or at least release Educational which really needs a new release).

**Pull request merged**
