### PR TITLE
Remove odl explain predictions widget

### PR DESCRIPTION
**Pull request by PrimozGodec**
##### Issue

There is now a newer explain widget in Prototypes which is based on SHAP library and is faster, this old widget now confuse users.

##### Description of changes
Removing the old widget. If we would like to re-add it we can revert this PR.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
This looks good. Perhaps remove the icon, too? Just to have a lean repo. :)

**Comment by PrimozGodec** [comment]
I didn't remove the icon since it is currently used as a temporary icon for explain models, explain prediction.

**Comment by ajdapretnar** [comment]
Yes, but these have their own files? So ExplainPredictions.svg can be removed, while ExplainModel.svg and ExplainPred.svg stay?

**Comment by PrimozGodec** [comment]
@ajdapretnar didn't notice that. :) I removed the icon.

**Pull request merged**
