### PR TITLE
GoogleSheets Revised

### PR DESCRIPTION
**Pull request by kernc**

### CODE REVIEW

**Comment by BlazZupan** [comment]
Does not work properly. Open

https://docs.google.com/spreadsheets/d/1SpWbuDk5CHSUjkmmniqsAU0YyE6qXG72l2lYSKkHMX8/edit?usp=sharing

with Google Sheets, set reload to 5s, connect to Data Table. Then start changing the table (change any value but do not change the length of the table. The changes in the google sheet data is not reflected in the Data Table.

**Comment by kernc** [comment]
Indeed, when reloading, it didn't output the new table if the number of lines hasn't increased. This was the naive approach to improving efficiency by avoiding to needlessly recompute the rest of the potentially complex workflow. Now switched to computing checksums over table payloads instead. Please try again.

**Comment by BlazZupan** [comment]
Crashes. Use

https://docs.google.com/spreadsheets/d/1SpWbuDk5CHSUjkmmniqsAU0YyE6qXG72l2lYSKkHMX8/edit?usp=sharing

and open with Google Sheets. Set refresh to 5 s. Go to data set in google sheet and write a number 1 somewhere in the column programmer (say, in the cell C12).

Please test more thoroughly before submission of next revision.

**Comment by kernc** [comment]
Sorry, I'm unable to reproduce the crash. Did tweak a little thingy that might have been it, but if you can get _this widget_ to error, I'd appreciate a backtrace.

**Comment by kernc** [comment]
The [issue](https://github.com/biolab/orange3-prototypes/pull/55#issuecomment-264719890) only manifests when BoxPlot is connected with changed discrete variable (i.e. C1, programmer) selected.

**Pull request merged**
