### PR TITLE
OWWebcamCapture: try capture devices in LIFO order

### PR DESCRIPTION
**Pull request by kernc**

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Works well for me. However, smaller screens evidently have issues with HD, so I cannot resize Webcam Capture. The idea was to set Webcam and Lookalike side-by-side. @VesnaT with your recent merge, I am able now to resize Lookalike and it works well on larger screen, yet when I tested this on my laptop with HD cam, things aren't as pretty. 😞 Ideas?

**Comment by kernc** [comment]
Please try again.

**Comment by ajdapretnar** [comment]
Works well on Windows, still having issues on Linux, but I presume it's just my Linux incompetence.

**Comment by kernc** [comment]
Resizing that QLabel was indeed something ...

How about now?

**Pull request merged**
