### PR TITLE
Add a face detection widget based on OpenCV.

### PR DESCRIPTION
**Pull request by thocevar**

### CODE REVIEW

**Comment by ajdapretnar** [comment]
You probably need to add an OpenCV dependency to requirements.txt. :) Otherwise look ok to me, only that I somewhat suspicious results (it's probably an issue of embeddings, so don't worry).

**Comment by ajdapretnar** [comment]
Oh, there's no requirements.txt in the first place. Anyway, widget is not working unless you manually install opencv.

**Comment by kernc** [comment]
OpenCV is _not_ pip-installable.

**Comment by ajdapretnar** [comment]
Yes, we'll sort it locally, for now.

**Pull request merged**
