### PR TITLE
Add Plotly-based OWParallelCoordinates

### PR DESCRIPTION
**Pull request by kernc**
##### Description of changes
Add Plotly-based Parallel Coordinates widget split from https://github.com/biolab/orange3/pull/2327 (where docs are, should ever be needed).

Requires https://github.com/biolab/orange3/issues/2761.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Um, I think you should disregard this issue, since I forgot to checkout biolab/orange3#2761.
Now I have it and widget... um... sort of works.

Current issues:
- selection on click extremely slow
- space between attributes (seems like between class, metas and features)
- again, probably a Mac thing, but when holding Ctrl/Cmd, I need to double click on an attribute to be selected... And again, when I move the cursor, sometimes attributes get delected without clicking anything... 😒

**Comment by ajdapretnar** [comment]
And regarding the space:
screen shot 2017-11-23 at 16 14 33

**Comment by jerneju** [comment]
@kernc : Please rebase.

**Comment by kernc** [comment]
List box items are ordered as `DomainModel` directs. Separators removed. First class default color.ž

Selection slowness unreproducible here. Mac issues are its own, and known about.

**Pull request merged**
