### PR TITLE
[ENH] CSV Import: Add CSV Import widget with preview and column type edit

### PR DESCRIPTION
**Pull request by ales-erjavec**
##### Issue

Need better support for importing data.

##### Description of changes

* Add a CSV Import widget with csv options and preview editing

screen shot 2018-07-04 at 13 13 55

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by borondics** [comment]
Great prototype and will be useful for many people. 

**Issue**
There is a problem, however: decimal delimiters. Currently, the code doesn't handle it well.

**Expected behavior**
Correctly read comma delimited floats.

**Actual behavior**
image

**Comment by borondics** [comment]
Could this widget be merged somehow into the File widget?

**Comment by ajdapretnar** [comment]
I like the changes. Error messages are great!
One more thing: it seems like the widget stores settings even when Orange is ran with --clear-widget-settings. 😕 Weird.

**Comment by ajdapretnar** [comment]
One more thing (sorry!). When I set the column to datetime, this doesn't have an effect in Orange. While the column displays the datetime icon, when checking in Select Columns, the attribute is a string...

**Comment by ales-erjavec** [comment]
>  When I set the column to datetime, this doesn't have an effect in Orange.

Should be fixed now.

**Comment by ajdapretnar** [comment]
No further comment. All looks great to me!

**Comment by lanzagar** [comment]
Works great for me. Let's merge into prototypes, and we can consider how to incorporate it into Orange after that. I agree merging into File somehow would be nice for the user, but I think integrating it well might not be so simple.

**Pull request merged**
