### PR TITLE
Remove Feature Statistics

### PR DESCRIPTION
**Pull request by pavlin-policar**
##### Issue
Remove Feature Statistics files after https://github.com/biolab/orange3/pull/3303 is merged into core.

##### Description of changes
Feature Statistics moved to core, remove from prototypes.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by markotoplak** [comment]
Even when it is merged into core, we should wait for some time before removing it here (at least until the Orange release that includes the widget; I would even wait for the next release).

**Comment by pavlin-policar** [comment]
Yeah, I agree. This can remain open until then.

**Comment by ajdapretnar** [comment]
How is this going? Are we ready to merge this or should we wait a bit?

**Comment by pavlin-policar** [comment]
I suppose now that Orange has been released at least once since we moved Feature statistics there, it should be removed here now.

**Pull request merged**
